# Generated by Django 5.1.7 on 2025-04-20 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment_date',
            field=models.TextField(blank=True, help_text='Instructions for the patient (previously instructions)', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment_time',
            field=models.TextField(blank=True, help_text='Prescribed medications (previously medication)', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Doctor's diagnosis (previously diagnosis)", null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lab_instructions',
            field=models.TextField(blank=True, help_text='Instructions for the lab technician', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lab_tests_required',
            field=models.BooleanField(blank=True, default=False, help_text='Whether lab tests are required', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Lab Tests'), ('completed', 'Completed')], default='pending', max_length=20, null=True),
        ),
    ]
