# Generated by Django 5.1.7 on 2025-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_text',
            field=models.TextField(blank=True, help_text="Doctor's prescription text", null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment_date',
            field=models.TextField(blank=True, help_text='Appointment date', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment_time',
            field=models.TextField(blank=True, help_text='Appointment time', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Patient's symptoms", null=True),
        ),
    ]
