# Generated by Django 5.1.7 on 2025-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consultation fee in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Education background and qualifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience for doctors', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='training',
            field=models.TextField(blank=True, help_text='Additional training and certifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Previous work places and experience details'),
        ),
    ]
