# Generated by Django 5.1.7 on 2025-04-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('medication', models.TextField(help_text='Prescribed medications')),
                ('instructions', models.TextField(help_text='Instructions for the patient')),
                ('lab_tests_required', models.BooleanField(default=False, help_text='Whether lab tests are required')),
                ('lab_instructions', models.TextField(blank=True, help_text='Instructions for the lab technician')),
                ('status', models.CharField(choices=[('pending', 'Pending Lab Tests'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('lab_technician', models.ForeignKey(blank=True, help_text='Assigned lab technician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
