# Generated by Django 5.1.7 on 2025-04-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_prescription_prescription_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, help_text="Doctor's full name with title", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_profession',
            field=models.CharField(blank=True, help_text="Doctor's specialty or profession", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='lab_results',
            field=models.TextField(blank=True, help_text='Results from lab tests', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, help_text="Patient's full name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment_date',
            field=models.CharField(blank=True, help_text='Date of the appointment (YYYY-MM-DD)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment_time',
            field=models.CharField(blank=True, help_text='Time of the appointment (HH:MM:SS)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor issuing the prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient receiving the prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
